// ─── Ease-Moji Emoji Database ──────────────────────────────────────
// Free set: ~600 emojis across 10 categories
// Premium adds: skin tone variants, flags, additional symbols,
// animated GIF stickers, and custom emoji art.

const FREE_EMOJIS = {
  "Smileys": [
    { e: "😀", n: "grinning face" },
    { e: "😃", n: "grinning face with big eyes" },
    { e: "😄", n: "grinning face with smiling eyes" },
    { e: "😁", n: "beaming face with smiling eyes" },
    { e: "😆", n: "grinning squinting face" },
    { e: "😅", n: "grinning face with sweat" },
    { e: "🤣", n: "rolling on the floor laughing" },
    { e: "😂", n: "face with tears of joy" },
    { e: "🙂", n: "slightly smiling face" },
    { e: "🙃", n: "upside-down face" },
    { e: "😉", n: "winking face" },
    { e: "😊", n: "smiling face with smiling eyes" },
    { e: "😇", n: "smiling face with halo" },
    { e: "🥰", n: "smiling face with hearts" },
    { e: "😍", n: "smiling face with heart-eyes" },
    { e: "🤩", n: "star-struck" },
    { e: "😘", n: "face blowing a kiss" },
    { e: "😗", n: "kissing face" },
    { e: "😚", n: "kissing face with closed eyes" },
    { e: "😙", n: "kissing face with smiling eyes" },
    { e: "😋", n: "face savoring food" },
    { e: "😛", n: "face with tongue" },
    { e: "😜", n: "winking face with tongue" },
    { e: "🤪", n: "zany face" },
    { e: "😝", n: "squinting face with tongue" },
    { e: "🤑", n: "money-mouth face" },
    { e: "🤗", n: "hugging face" },
    { e: "🤭", n: "face with hand over mouth" },
    { e: "🤫", n: "shushing face" },
    { e: "🤔", n: "thinking face" },
    { e: "🤐", n: "zipper-mouth face" },
    { e: "🤨", n: "face with raised eyebrow" },
    { e: "😐", n: "neutral face" },
    { e: "😑", n: "expressionless face" },
    { e: "😶", n: "face without mouth" },
    { e: "😏", n: "smirking face" },
    { e: "😒", n: "unamused face" },
    { e: "🙄", n: "face with rolling eyes" },
    { e: "😬", n: "grimacing face" },
    { e: "😮", n: "face with open mouth" },
    { e: "😯", n: "hushed face" },
    { e: "😲", n: "astonished face" },
    { e: "😳", n: "flushed face" },
    { e: "🥺", n: "pleading face" },
    { e: "😦", n: "frowning face with open mouth" },
    { e: "😧", n: "anguished face" },
    { e: "😨", n: "fearful face" },
    { e: "😰", n: "anxious face with sweat" },
    { e: "😥", n: "sad but relieved face" },
    { e: "😢", n: "crying face" },
    { e: "😭", n: "loudly crying face" },
    { e: "😱", n: "face screaming in fear" },
    { e: "😖", n: "confounded face" },
    { e: "😣", n: "persevering face" },
    { e: "😞", n: "disappointed face" },
    { e: "😓", n: "downcast face with sweat" },
    { e: "😩", n: "weary face" },
    { e: "😫", n: "tired face" },
    { e: "🥱", n: "yawning face" },
    { e: "😤", n: "face with steam from nose" },
    { e: "😡", n: "pouting face" },
    { e: "😠", n: "angry face" },
    { e: "🤬", n: "face with symbols on mouth" },
    { e: "😈", n: "smiling face with horns" },
    { e: "👿", n: "angry face with horns" },
    { e: "💀", n: "skull" },
    { e: "☠️", n: "skull and crossbones" },
    { e: "💩", n: "pile of poo" },
    { e: "🤡", n: "clown face" },
    { e: "👹", n: "ogre" },
    { e: "👺", n: "goblin" },
    { e: "👻", n: "ghost" },
    { e: "👽", n: "alien" },
    { e: "👾", n: "alien monster" },
    { e: "🤖", n: "robot" },
    { e: "😺", n: "grinning cat" },
    { e: "😸", n: "grinning cat with smiling eyes" },
    { e: "😹", n: "cat with tears of joy" },
    { e: "😻", n: "smiling cat with heart-eyes" },
    { e: "😼", n: "cat with wry smile" },
    { e: "😽", n: "kissing cat" },
    { e: "🙀", n: "weary cat" },
    { e: "😿", n: "crying cat" },
    { e: "😾", n: "pouting cat" },
    { e: "💋", n: "kiss mark" },
    { e: "💌", n: "love letter" },
    { e: "💘", n: "heart with arrow" },
    { e: "💝", n: "heart with ribbon" },
    { e: "💖", n: "sparkling heart" },
    { e: "💗", n: "growing heart" },
    { e: "💓", n: "beating heart" },
    { e: "💞", n: "revolving hearts" },
    { e: "💕", n: "two hearts" },
    { e: "💟", n: "heart decoration" },
    { e: "❤️", n: "red heart" },
    { e: "🧡", n: "orange heart" },
    { e: "💛", n: "yellow heart" },
    { e: "💚", n: "green heart" },
    { e: "💙", n: "blue heart" },
    { e: "💜", n: "purple heart" },
    { e: "🖤", n: "black heart" },
    { e: "🤍", n: "white heart" },
    { e: "🤎", n: "brown heart" },
    { e: "💔", n: "broken heart" },
    { e: "❣️", n: "heart exclamation" },
    { e: "💯", n: "hundred points" },
    { e: "💢", n: "anger symbol" },
    { e: "💥", n: "collision" },
    { e: "💫", n: "dizzy" },
    { e: "💦", n: "sweat droplets" },
    { e: "💨", n: "dashing away" },
  ],

  "Gestures & People": [
    { e: "👋", n: "waving hand" },
    { e: "🤚", n: "raised back of hand" },
    { e: "🖐️", n: "hand with fingers splayed" },
    { e: "✋", n: "raised hand" },
    { e: "🖖", n: "vulcan salute" },
    { e: "👌", n: "OK hand" },
    { e: "🤌", n: "pinched fingers" },
    { e: "🤏", n: "pinching hand" },
    { e: "✌️", n: "victory hand" },
    { e: "🤞", n: "crossed fingers" },
    { e: "🤟", n: "love-you gesture" },
    { e: "🤘", n: "sign of the horns" },
    { e: "🤙", n: "call me hand" },
    { e: "👈", n: "backhand index pointing left" },
    { e: "👉", n: "backhand index pointing right" },
    { e: "👆", n: "backhand index pointing up" },
    { e: "🖕", n: "middle finger" },
    { e: "👇", n: "backhand index pointing down" },
    { e: "☝️", n: "index pointing up" },
    { e: "🫵", n: "index pointing at the viewer" },
    { e: "👍", n: "thumbs up" },
    { e: "👎", n: "thumbs down" },
    { e: "✊", n: "raised fist" },
    { e: "👊", n: "oncoming fist" },
    { e: "🤛", n: "left-facing fist" },
    { e: "🤜", n: "right-facing fist" },
    { e: "👏", n: "clapping hands" },
    { e: "🙌", n: "raising hands" },
    { e: "👐", n: "open hands" },
    { e: "🤲", n: "palms up together" },
    { e: "🤝", n: "handshake" },
    { e: "🙏", n: "folded hands" },
    { e: "✍️", n: "writing hand" },
    { e: "💅", n: "nail polish" },
    { e: "🤳", n: "selfie" },
    { e: "💪", n: "flexed biceps" },
    { e: "🦵", n: "leg" },
    { e: "🦶", n: "foot" },
    { e: "👂", n: "ear" },
    { e: "👃", n: "nose" },
    { e: "🧠", n: "brain" },
    { e: "🫀", n: "anatomical heart" },
    { e: "🫁", n: "lungs" },
    { e: "🦷", n: "tooth" },
    { e: "👅", n: "tongue" },
    { e: "👁️", n: "eye" },
    { e: "👀", n: "eyes" },
    { e: "👤", n: "bust in silhouette" },
    { e: "👥", n: "busts in silhouette" },
    { e: "🗣️", n: "speaking head" },
    { e: "👶", n: "baby" },
    { e: "🧒", n: "child" },
    { e: "👦", n: "boy" },
    { e: "👧", n: "girl" },
    { e: "🧑", n: "person" },
    { e: "👨", n: "man" },
    { e: "👩", n: "woman" },
    { e: "🧔", n: "person: beard" },
    { e: "👴", n: "old man" },
    { e: "👵", n: "old woman" },
  ],

  "Nature": [
    { e: "🐶", n: "dog face" },
    { e: "🐱", n: "cat face" },
    { e: "🐭", n: "mouse face" },
    { e: "🐹", n: "hamster" },
    { e: "🐰", n: "rabbit face" },
    { e: "🦊", n: "fox" },
    { e: "🐻", n: "bear" },
    { e: "🐼", n: "panda" },
    { e: "🐨", n: "koala" },
    { e: "🐯", n: "tiger face" },
    { e: "🦁", n: "lion" },
    { e: "🐮", n: "cow face" },
    { e: "🐷", n: "pig face" },
    { e: "🐸", n: "frog" },
    { e: "🐵", n: "monkey face" },
    { e: "🐔", n: "chicken" },
    { e: "🐧", n: "penguin" },
    { e: "🐦", n: "bird" },
    { e: "🐤", n: "baby chick" },
    { e: "🦆", n: "duck" },
    { e: "🦅", n: "eagle" },
    { e: "🦉", n: "owl" },
    { e: "🦇", n: "bat" },
    { e: "🐺", n: "wolf" },
    { e: "🐗", n: "boar" },
    { e: "🐴", n: "horse face" },
    { e: "🦄", n: "unicorn" },
    { e: "🐝", n: "honeybee" },
    { e: "🐛", n: "bug" },
    { e: "🦋", n: "butterfly" },
    { e: "🐌", n: "snail" },
    { e: "🐞", n: "lady beetle" },
    { e: "🐜", n: "ant" },
    { e: "🦟", n: "mosquito" },
    { e: "🦗", n: "cricket" },
    { e: "🪳", n: "cockroach" },
    { e: "🦂", n: "scorpion" },
    { e: "🐢", n: "turtle" },
    { e: "🐍", n: "snake" },
    { e: "🦎", n: "lizard" },
    { e: "🦖", n: "T-Rex" },
    { e: "🦕", n: "sauropod" },
    { e: "🐙", n: "octopus" },
    { e: "🦑", n: "squid" },
    { e: "🦐", n: "shrimp" },
    { e: "🐠", n: "tropical fish" },
    { e: "🐟", n: "fish" },
    { e: "🐡", n: "blowfish" },
    { e: "🐬", n: "dolphin" },
    { e: "🐳", n: "spouting whale" },
    { e: "🐋", n: "whale" },
    { e: "🦈", n: "shark" },
    { e: "🌱", n: "seedling" },
    { e: "🌿", n: "herb" },
    { e: "☘️", n: "shamrock" },
    { e: "🍀", n: "four leaf clover" },
    { e: "🌲", n: "evergreen tree" },
    { e: "🌳", n: "deciduous tree" },
    { e: "🌴", n: "palm tree" },
    { e: "🌵", n: "cactus" },
    { e: "🌾", n: "sheaf of rice" },
    { e: "🌻", n: "sunflower" },
    { e: "🌹", n: "rose" },
    { e: "🌷", n: "tulip" },
    { e: "🌸", n: "cherry blossom" },
    { e: "💐", n: "bouquet" },
    { e: "🍄", n: "mushroom" },
    { e: "🌍", n: "globe showing Europe-Africa" },
    { e: "🌎", n: "globe showing Americas" },
    { e: "🌏", n: "globe showing Asia-Australia" },
    { e: "🌕", n: "full moon" },
    { e: "🌙", n: "crescent moon" },
    { e: "⭐", n: "star" },
    { e: "🌟", n: "glowing star" },
    { e: "☀️", n: "sun" },
    { e: "🌈", n: "rainbow" },
    { e: "☁️", n: "cloud" },
    { e: "⛅", n: "sun behind cloud" },
    { e: "⚡", n: "high voltage" },
    { e: "❄️", n: "snowflake" },
    { e: "🔥", n: "fire" },
    { e: "💧", n: "droplet" },
    { e: "🌊", n: "water wave" },
  ],

  "Food & Drink": [
    { e: "🍏", n: "green apple" },
    { e: "🍎", n: "red apple" },
    { e: "🍐", n: "pear" },
    { e: "🍊", n: "tangerine" },
    { e: "🍋", n: "lemon" },
    { e: "🍌", n: "banana" },
    { e: "🍉", n: "watermelon" },
    { e: "🍇", n: "grapes" },
    { e: "🍓", n: "strawberry" },
    { e: "🫐", n: "blueberries" },
    { e: "🍈", n: "melon" },
    { e: "🍒", n: "cherries" },
    { e: "🍑", n: "peach" },
    { e: "🥭", n: "mango" },
    { e: "🍍", n: "pineapple" },
    { e: "🥝", n: "kiwi" },
    { e: "🍅", n: "tomato" },
    { e: "🥑", n: "avocado" },
    { e: "🥦", n: "broccoli" },
    { e: "🥬", n: "leafy green" },
    { e: "🥒", n: "cucumber" },
    { e: "🌽", n: "ear of corn" },
    { e: "🥕", n: "carrot" },
    { e: "🧅", n: "onion" },
    { e: "🧄", n: "garlic" },
    { e: "🥔", n: "potato" },
    { e: "🍠", n: "roasted sweet potato" },
    { e: "🥜", n: "peanuts" },
    { e: "🍞", n: "bread" },
    { e: "🥐", n: "croissant" },
    { e: "🥖", n: "baguette bread" },
    { e: "🧀", n: "cheese wedge" },
    { e: "🥚", n: "egg" },
    { e: "🍳", n: "cooking" },
    { e: "🥓", n: "bacon" },
    { e: "🥩", n: "cut of meat" },
    { e: "🍔", n: "hamburger" },
    { e: "🍟", n: "french fries" },
    { e: "🌭", n: "hot dog" },
    { e: "🍕", n: "pizza" },
    { e: "🫓", n: "flatbread" },
    { e: "🥪", n: "sandwich" },
    { e: "🌮", n: "taco" },
    { e: "🌯", n: "burrito" },
    { e: "🥗", n: "salad" },
    { e: "🍜", n: "steaming bowl" },
    { e: "🍝", n: "spaghetti" },
    { e: "🍣", n: "sushi" },
    { e: "🍱", n: "bento box" },
    { e: "🍛", n: "curry rice" },
    { e: "🍙", n: "rice ball" },
    { e: "🍚", n: "cooked rice" },
    { e: "🍘", n: "rice cracker" },
    { e: "🥟", n: "dumpling" },
    { e: "🥠", n: "fortune cookie" },
    { e: "🍦", n: "soft ice cream" },
    { e: "🍧", n: "shaved ice" },
    { e: "🍨", n: "ice cream" },
    { e: "🍩", n: "doughnut" },
    { e: "🍪", n: "cookie" },
    { e: "🎂", n: "birthday cake" },
    { e: "🍰", n: "shortcake" },
    { e: "🧁", n: "cupcake" },
    { e: "🥧", n: "pie" },
    { e: "🍫", n: "chocolate bar" },
    { e: "🍬", n: "candy" },
    { e: "🍭", n: "lollipop" },
    { e: "🍮", n: "custard" },
    { e: "🍯", n: "honey pot" },
    { e: "☕", n: "hot beverage" },
    { e: "🫖", n: "teapot" },
    { e: "🍵", n: "teacup without handle" },
    { e: "🧋", n: "bubble tea" },
    { e: "🥤", n: "cup with straw" },
    { e: "🧃", n: "beverage box" },
    { e: "🍺", n: "beer mug" },
    { e: "🍻", n: "clinking beer mugs" },
    { e: "🥂", n: "clinking glasses" },
    { e: "🍷", n: "wine glass" },
    { e: "🥃", n: "tumbler glass" },
    { e: "🍸", n: "cocktail glass" },
    { e: "🍹", n: "tropical drink" },
    { e: "🧊", n: "ice" },
  ],

  "Travel & Places": [
    { e: "🚗", n: "car" },
    { e: "🚕", n: "taxi" },
    { e: "🚙", n: "SUV" },
    { e: "🚌", n: "bus" },
    { e: "🚎", n: "trolleybus" },
    { e: "🚓", n: "police car" },
    { e: "🚑", n: "ambulance" },
    { e: "🚒", n: "fire engine" },
    { e: "🚐", n: "minibus" },
    { e: "🚚", n: "delivery truck" },
    { e: "🚛", n: "articulated lorry" },
    { e: "🚜", n: "tractor" },
    { e: "🏎️", n: "racing car" },
    { e: "🏍️", n: "motorcycle" },
    { e: "🛵", n: "motor scooter" },
    { e: "🛴", n: "kick scooter" },
    { e: "🚲", n: "bicycle" },
    { e: "🛹", n: "skateboard" },
    { e: "🚏", n: "bus stop" },
    { e: "🛣️", n: "motorway" },
    { e: "🛤️", n: "railway track" },
    { e: "🚂", n: "locomotive" },
    { e: "🚃", n: "railway car" },
    { e: "🚄", n: "high-speed train" },
    { e: "🚅", n: "bullet train" },
    { e: "🚇", n: "metro" },
    { e: "🚉", n: "station" },
    { e: "✈️", n: "airplane" },
    { e: "🛫", n: "airplane departure" },
    { e: "🛬", n: "airplane arrival" },
    { e: "🛩️", n: "small airplane" },
    { e: "🚁", n: "helicopter" },
    { e: "🛸", n: "flying saucer" },
    { e: "🚀", n: "rocket" },
    { e: "🛰️", n: "satellite" },
    { e: "💺", n: "seat" },
    { e: "🚢", n: "ship" },
    { e: "⛵", n: "sailboat" },
    { e: "🛶", n: "canoe" },
    { e: "🚤", n: "speedboat" },
    { e: "🛳️", n: "passenger ship" },
    { e: "🗺️", n: "world map" },
    { e: "🏠", n: "house" },
    { e: "🏡", n: "house with garden" },
    { e: "🏢", n: "office building" },
    { e: "🏣", n: "Japanese post office" },
    { e: "🏤", n: "post office" },
    { e: "🏥", n: "hospital" },
    { e: "🏦", n: "bank" },
    { e: "🏨", n: "hotel" },
    { e: "🏩", n: "love hotel" },
    { e: "🏪", n: "convenience store" },
    { e: "🏫", n: "school" },
    { e: "🏬", n: "department store" },
    { e: "🏭", n: "factory" },
    { e: "🏯", n: "Japanese castle" },
    { e: "🏰", n: "castle" },
    { e: "💒", n: "wedding" },
    { e: "🗼", n: "Tokyo Tower" },
    { e: "🗽", n: "Statue of Liberty" },
    { e: "⛪", n: "church" },
    { e: "🕌", n: "mosque" },
    { e: "🛕", n: "hindu temple" },
    { e: "🕍", n: "synagogue" },
    { e: "⛩️", n: "shinto shrine" },
    { e: "🏛️", n: "classical building" },
    { e: "🌄", n: "sunrise over mountains" },
    { e: "🌅", n: "sunrise" },
    { e: "🌇", n: "sunset" },
    { e: "🏖️", n: "beach with umbrella" },
    { e: "🏔️", n: "snow-capped mountain" },
    { e: "🏕️", n: "camping" },
    { e: "🏜️", n: "desert" },
    { e: "🏝️", n: "desert island" },
    { e: "🏗️", n: "building construction" },
  ],

  "Activities": [
    { e: "⚽", n: "soccer ball" },
    { e: "🏀", n: "basketball" },
    { e: "🏈", n: "American football" },
    { e: "⚾", n: "baseball" },
    { e: "🥎", n: "softball" },
    { e: "🎾", n: "tennis" },
    { e: "🏐", n: "volleyball" },
    { e: "🏉", n: "rugby football" },
    { e: "🥏", n: "flying disc" },
    { e: "🎳", n: "bowling" },
    { e: "🏏", n: "cricket game" },
    { e: "🏑", n: "field hockey" },
    { e: "🥍", n: "lacrosse" },
    { e: "⛳", n: "flag in hole" },
    { e: "🏌️", n: "person golfing" },
    { e: "🎣", n: "fishing pole" },
    { e: "🤿", n: "diving mask" },
    { e: "🎽", n: "running shirt" },
    { e: "🎿", n: "skis" },
    { e: "🛷", n: "sled" },
    { e: "🥌", n: "curling stone" },
    { e: "🎯", n: "bullseye" },
    { e: "🎱", n: "pool 8 ball" },
    { e: "🎮", n: "video game" },
    { e: "🎰", n: "slot machine" },
    { e: "🎲", n: "game die" },
    { e: "♟️", n: "chess pawn" },
    { e: "🎭", n: "performing arts" },
    { e: "🎨", n: "artist palette" },
    { e: "🎬", n: "clapper board" },
    { e: "🎤", n: "microphone" },
    { e: "🎧", n: "headphone" },
    { e: "🎼", n: "musical score" },
    { e: "🎹", n: "musical keyboard" },
    { e: "🥁", n: "drum" },
    { e: "🎷", n: "saxophone" },
    { e: "🎺", n: "trumpet" },
    { e: "🎸", n: "guitar" },
    { e: "🎻", n: "violin" },
    { e: "🪕", n: "banjo" },
    { e: "🎙️", n: "studio microphone" },
    { e: "📻", n: "radio" },
    { e: "🎵", n: "musical note" },
    { e: "🎶", n: "musical notes" },
    { e: "📀", n: "DVD" },
    { e: "💿", n: "CD" },
    { e: "📸", n: "camera with flash" },
    { e: "📷", n: "camera" },
    { e: "🎥", n: "movie camera" },
    { e: "📹", n: "video camera" },
    { e: "📺", n: "television" },
    { e: "📱", n: "mobile phone" },
    { e: "💻", n: "laptop" },
    { e: "⌨️", n: "keyboard" },
    { e: "🖥️", n: "desktop computer" },
    { e: "🖨️", n: "printer" },
    { e: "🕹️", n: "joystick" },
  ],

  "Objects": [
    { e: "⌚", n: "watch" },
    { e: "📱", n: "mobile phone" },
    { e: "💻", n: "laptop" },
    { e: "⌨️", n: "keyboard" },
    { e: "🖥️", n: "desktop computer" },
    { e: "🖨️", n: "printer" },
    { e: "🖱️", n: "computer mouse" },
    { e: "🖲️", n: "trackball" },
    { e: "🔋", n: "battery" },
    { e: "🔌", n: "electric plug" },
    { e: "💡", n: "light bulb" },
    { e: "🔦", n: "flashlight" },
    { e: "🕯️", n: "candle" },
    { e: "📖", n: "open book" },
    { e: "📕", n: "closed book" },
    { e: "📗", n: "green book" },
    { e: "📘", n: "blue book" },
    { e: "📙", n: "orange book" },
    { e: "📚", n: "books" },
    { e: "📓", n: "notebook" },
    { e: "📒", n: "ledger" },
    { e: "📃", n: "page with curl" },
    { e: "📜", n: "scroll" },
    { e: "📄", n: "page facing up" },
    { e: "📰", n: "newspaper" },
    { e: "📑", n: "bookmark tabs" },
    { e: "🔖", n: "bookmark" },
    { e: "💰", n: "money bag" },
    { e: "💴", n: "yen banknote" },
    { e: "💵", n: "dollar banknote" },
    { e: "💶", n: "euro banknote" },
    { e: "💷", n: "pound banknote" },
    { e: "💳", n: "credit card" },
    { e: "🧾", n: "receipt" },
    { e: "✉️", n: "envelope" },
    { e: "📧", n: "e-mail" },
    { e: "📨", n: "incoming envelope" },
    { e: "📩", n: "envelope with arrow" },
    { e: "📤", n: "outbox tray" },
    { e: "📥", n: "inbox tray" },
    { e: "📦", n: "package" },
    { e: "📫", n: "closed mailbox with raised flag" },
    { e: "📪", n: "closed mailbox with lowered flag" },
    { e: "📬", n: "open mailbox with raised flag" },
    { e: "📭", n: "open mailbox with lowered flag" },
    { e: "📮", n: "postbox" },
    { e: "✏️", n: "pencil" },
    { e: "✒️", n: "black nib" },
    { e: "🖊️", n: "pen" },
    { e: "🖌️", n: "paintbrush" },
    { e: "🖍️", n: "crayon" },
    { e: "📎", n: "paperclip" },
    { e: "🖇️", n: "linked paperclips" },
    { e: "📏", n: "straight ruler" },
    { e: "📐", n: "triangular ruler" },
    { e: "✂️", n: "scissors" },
    { e: "🗃️", n: "card file box" },
    { e: "🗄️", n: "file cabinet" },
    { e: "🔑", n: "key" },
    { e: "🗝️", n: "old key" },
    { e: "🔨", n: "hammer" },
    { e: "🪓", n: "axe" },
    { e: "⛏️", n: "pick" },
    { e: "🔧", n: "wrench" },
    { e: "🔩", n: "nut and bolt" },
    { e: "🔫", n: "pistol" },
    { e: "🛠️", n: "hammer and wrench" },
    { e: "🧰", n: "toolbox" },
    { e: "🔗", n: "link" },
    { e: "⛓️", n: "chains" },
    { e: "🧲", n: "magnet" },
    { e: "🔬", n: "microscope" },
    { e: "🔭", n: "telescope" },
    { e: "📡", n: "satellite antenna" },
    { e: "💉", n: "syringe" },
    { e: "🩺", n: "stethoscope" },
    { e: "💊", n: "pill" },
    { e: "🩹", n: "adhesive bandage" },
    { e: "🚪", n: "door" },
    { e: "🛏️", n: "bed" },
    { e: "🛋️", n: "couch and lamp" },
    { e: "🚽", n: "toilet" },
    { e: "🚿", n: "shower" },
    { e: "🛁", n: "bathtub" },
    { e: "🧹", n: "broom" },
    { e: "🧻", n: "roll of paper" },
    { e: "🔪", n: "knife" },
    { e: "🍽️", n: "fork and knife with plate" },
    { e: "🪴", n: "potted plant" },
  ],

  "Symbols": [
    { e: "❤️", n: "red heart" },
    { e: "🧡", n: "orange heart" },
    { e: "💛", n: "yellow heart" },
    { e: "💚", n: "green heart" },
    { e: "💙", n: "blue heart" },
    { e: "💜", n: "purple heart" },
    { e: "🖤", n: "black heart" },
    { e: "🤍", n: "white heart" },
    { e: "🤎", n: "brown heart" },
    { e: "💔", n: "broken heart" },
    { e: "❣️", n: "heart exclamation" },
    { e: "💕", n: "two hearts" },
    { e: "💞", n: "revolving hearts" },
    { e: "💓", n: "beating heart" },
    { e: "💗", n: "growing heart" },
    { e: "💖", n: "sparkling heart" },
    { e: "💘", n: "heart with arrow" },
    { e: "💝", n: "heart with ribbon" },
    { e: "💟", n: "heart decoration" },
    { e: "☮️", n: "peace symbol" },
    { e: "✝️", n: "latin cross" },
    { e: "☪️", n: "star and crescent" },
    { e: "☸️", n: "wheel of dharma" },
    { e: "✡️", n: "star of David" },
    { e: "🔯", n: "six pointed star" },
    { e: "🕉️", n: "om" },
    { e: "☯️", n: "yin yang" },
    { e: "🛐", n: "place of worship" },
    { e: "♈", n: "Aries" },
    { e: "♉", n: "Taurus" },
    { e: "♊", n: "Gemini" },
    { e: "♋", n: "Cancer" },
    { e: "♌", n: "Leo" },
    { e: "♍", n: "Virgo" },
    { e: "♎", n: "Libra" },
    { e: "♏", n: "Scorpio" },
    { e: "♐", n: "Sagittarius" },
    { e: "♑", n: "Capricorn" },
    { e: "♒", n: "Aquarius" },
    { e: "♓", n: "Pisces" },
    { e: "⛎", n: "Ophiuchus" },
    { e: "🆔", n: "ID button" },
    { e: "🆕", n: "NEW button" },
    { e: "🆖", n: "NG button" },
    { e: "🆗", n: "OK button" },
    { e: "🆘", n: "SOS button" },
    { e: "🆙", n: "UP! button" },
    { e: "🆒", n: "COOL button" },
    { e: "🆓", n: "FREE button" },
    { e: "ℹ️", n: "information" },
    { e: "🆚", n: "VS button" },
    { e: "🚮", n: "litter in bin sign" },
    { e: "🚰", n: "potable water" },
    { e: "♻️", n: "recycling symbol" },
    { e: "🚹", n: "men's room" },
    { e: "🚺", n: "women's room" },
    { e: "🚻", n: "restroom" },
    { e: "🚼", n: "baby symbol" },
    { e: "🚾", n: "water closet" },
    { e: "⚠️", n: "warning" },
    { e: "🚸", n: "children crossing" },
    { e: "⛔", n: "no entry" },
    { e: "🚫", n: "prohibited" },
    { e: "🚳", n: "no bicycles" },
    { e: "🚭", n: "no smoking" },
    { e: "🚯", n: "no littering" },
    { e: "🚱", n: "non-potable water" },
    { e: "📵", n: "no mobile phones" },
    { e: "🔞", n: "no one under eighteen" },
    { e: "☢️", n: "radioactive" },
    { e: "☣️", n: "biohazard" },
    { e: "⬆️", n: "up arrow" },
    { e: "⬇️", n: "down arrow" },
    { e: "⬅️", n: "left arrow" },
    { e: "➡️", n: "right arrow" },
    { e: "🔃", n: "clockwise vertical arrows" },
    { e: "🔄", n: "counterclockwise arrows button" },
    { e: "🔙", n: "BACK arrow" },
    { e: "🔚", n: "END arrow" },
    { e: "🔛", n: "ON! arrow" },
    { e: "🔜", n: "SOON arrow" },
    { e: "🔝", n: "TOP arrow" },
    { e: "✅", n: "check mark button" },
    { e: "❌", n: "cross mark" },
    { e: "❓", n: "question mark" },
    { e: "❗", n: "exclamation mark" },
    { e: "➕", n: "plus" },
    { e: "➖", n: "minus" },
    { e: "➗", n: "divide" },
    { e: "♠️", n: "spade suit" },
    { e: "♥️", n: "heart suit" },
    { e: "♦️", n: "diamond suit" },
    { e: "♣️", n: "club suit" },
    { e: "♟️", n: "chess pawn" },
    { e: "🃏", n: "joker" },
    { e: "🎴", n: "flower playing cards" },
    { e: "🔴", n: "red circle" },
    { e: "🟠", n: "orange circle" },
    { e: "🟡", n: "yellow circle" },
    { e: "🟢", n: "green circle" },
    { e: "🔵", n: "blue circle" },
    { e: "🟣", n: "purple circle" },
    { e: "⚪", n: "white circle" },
    { e: "🟤", n: "brown circle" },
    { e: "⚫", n: "black circle" },
    { e: "🟥", n: "red square" },
    { e: "🟧", n: "orange square" },
    { e: "🟨", n: "yellow square" },
    { e: "🟩", n: "green square" },
    { e: "🟦", n: "blue square" },
    { e: "🟪", n: "purple square" },
    { e: "⬜", n: "white large square" },
    { e: "🟫", n: "brown square" },
    { e: "⬛", n: "black large square" },
  ],
};

// ── Premium-only emojis: flags, skin tone variants, extra symbols ──
// These are only shown when `premium.active` is true.

const PREMIUM_EMOJIS = {
  "Flags": [
    { e: "🏳️", n: "white flag" },
    { e: "🏴", n: "black flag" },
    { e: "🏁", n: "checkered flag" },
    { e: "🚩", n: "triangular flag" },
    { e: "🏳️‍🌈", n: "rainbow flag" },
    { e: "🏳️‍⚧️", n: "transgender flag" },
    { e: "🇺🇳", n: "United Nations" },
    { e: "🇺🇸", n: "United States" },
    { e: "🇬🇧", n: "United Kingdom" },
    { e: "🇨🇦", n: "Canada" },
    { e: "🇦🇺", n: "Australia" },
    { e: "🇯🇵", n: "Japan" },
    { e: "🇩🇪", n: "Germany" },
    { e: "🇫🇷", n: "France" },
    { e: "🇮🇹", n: "Italy" },
    { e: "🇪🇸", n: "Spain" },
    { e: "🇧🇷", n: "Brazil" },
    { e: "🇮🇳", n: "India" },
    { e: "🇨🇳", n: "China" },
    { e: "🇰🇷", n: "South Korea" },
    { e: "🇲🇽", n: "Mexico" },
    { e: "🇷🇺", n: "Russia" },
    { e: "🇿🇦", n: "South Africa" },
    { e: "🇸🇪", n: "Sweden" },
    { e: "🇳🇴", n: "Norway" },
    { e: "🇩🇰", n: "Denmark" },
    { e: "🇫🇮", n: "Finland" },
    { e: "🇳🇱", n: "Netherlands" },
    { e: "🇧🇪", n: "Belgium" },
    { e: "🇨🇭", n: "Switzerland" },
    { e: "🇦🇹", n: "Austria" },
    { e: "🇮🇪", n: "Ireland" },
    { e: "🇵🇹", n: "Portugal" },
    { e: "🇬🇷", n: "Greece" },
    { e: "🇵🇱", n: "Poland" },
    { e: "🇨🇿", n: "Czechia" },
    { e: "🇭🇺", n: "Hungary" },
    { e: "🇹🇷", n: "Turkey" },
    { e: "🇮🇱", n: "Israel" },
    { e: "🇸🇦", n: "Saudi Arabia" },
    { e: "🇦🇪", n: "United Arab Emirates" },
    { e: "🇸🇬", n: "Singapore" },
    { e: "🇭🇰", n: "Hong Kong" },
    { e: "🇹🇼", n: "Taiwan" },
    { e: "🇦🇷", n: "Argentina" },
    { e: "🇨🇱", n: "Chile" },
    { e: "🇨🇴", n: "Colombia" },
    { e: "🇳🇬", n: "Nigeria" },
    { e: "🇰🇪", n: "Kenya" },
    { e: "🇪🇬", n: "Egypt" },
    { e: "🇹🇭", n: "Thailand" },
    { e: "🇻🇳", n: "Vietnam" },
    { e: "🇮🇩", n: "Indonesia" },
    { e: "🇵🇭", n: "Philippines" },
    { e: "🇲🇾", n: "Malaysia" },
    { e: "🇳🇿", n: "New Zealand" },
  ],

  "Skin Tones": [
    { e: "👋🏻", n: "waving hand: light" },
    { e: "👋🏼", n: "waving hand: medium-light" },
    { e: "👋🏽", n: "waving hand: medium" },
    { e: "👋🏾", n: "waving hand: medium-dark" },
    { e: "👋🏿", n: "waving hand: dark" },
    { e: "👍🏻", n: "thumbs up: light" },
    { e: "👍🏼", n: "thumbs up: medium-light" },
    { e: "👍🏽", n: "thumbs up: medium" },
    { e: "👍🏾", n: "thumbs up: medium-dark" },
    { e: "👍🏿", n: "thumbs up: dark" },
    { e: "👎🏻", n: "thumbs down: light" },
    { e: "👎🏼", n: "thumbs down: medium-light" },
    { e: "👎🏽", n: "thumbs down: medium" },
    { e: "👎🏾", n: "thumbs down: medium-dark" },
    { e: "👎🏿", n: "thumbs down: dark" },
    { e: "✊🏻", n: "raised fist: light" },
    { e: "✊🏼", n: "raised fist: medium-light" },
    { e: "✊🏽", n: "raised fist: medium" },
    { e: "✊🏾", n: "raised fist: medium-dark" },
    { e: "✊🏿", n: "raised fist: dark" },
    { e: "👊🏻", n: "oncoming fist: light" },
    { e: "👊🏼", n: "oncoming fist: medium-light" },
    { e: "👊🏽", n: "oncoming fist: medium" },
    { e: "👊🏾", n: "oncoming fist: medium-dark" },
    { e: "👊🏿", n: "oncoming fist: dark" },
    { e: "🙏🏻", n: "folded hands: light" },
    { e: "🙏🏼", n: "folded hands: medium-light" },
    { e: "🙏🏽", n: "folded hands: medium" },
    { e: "🙏🏾", n: "folded hands: medium-dark" },
    { e: "🙏🏿", n: "folded hands: dark" },
  ],

  "Premium Stickers": [
    { e: "🎉", n: "party popper" },
    { e: "🎊", n: "confetti ball" },
    { e: "🎈", n: "balloon" },
    { e: "🎁", n: "wrapped gift" },
    { e: "🏆", n: "trophy" },
    { e: "🥇", n: "1st place medal" },
    { e: "🥈", n: "2nd place medal" },
    { e: "🥉", n: "3rd place medal" },
    { e: "🎖️", n: "military medal" },
    { e: "🏅", n: "sports medal" },
    { e: "🎗️", n: "reminder ribbon" },
    { e: "👑", n: "crown" },
    { e: "💎", n: "gem stone" },
    { e: "🔮", n: "crystal ball" },
    { e: "🪄", n: "magic wand" },
    { e: "✨", n: "sparkles" },
    { e: "🌟", n: "glowing star" },
    { e: "⭐", n: "star" },
    { e: "🌈", n: "rainbow" },
    { e: "🦋", n: "butterfly" },
    { e: "🌸", n: "cherry blossom" },
    { e: "🌺", n: "hibiscus" },
    { e: "🌻", n: "sunflower" },
    { e: "🌹", n: "rose" },
    { e: "🌷", n: "tulip" },
    { e: "💐", n: "bouquet" },
    { e: "🦄", n: "unicorn" },
  ],
};

// ── Search index: maps lowercase keywords to emojis ─────────────

function buildSearchIndex() {
  const index = new Map();

  function add(category, items) {
    for (const item of items) {
      const terms = item.n.toLowerCase().split(/[\s,]+/);
      for (const term of terms) {
        if (!index.has(term)) index.set(term, []);
        index.get(term).push({ ...item, category });
      }
    }
  }

  for (const [cat, items] of Object.entries(FREE_EMOJIS)) {
    add(cat, items);
  }
  for (const [cat, items] of Object.entries(PREMIUM_EMOJIS)) {
    add(cat, items);
  }

  return index;
}

const SEARCH_INDEX = buildSearchIndex();

// ── Exports ───────────────────────────────────────────────────

export { FREE_EMOJIS, PREMIUM_EMOJIS, SEARCH_INDEX };
